const machineList = [
  {
    machine_no: 1,
    machine_name: "Machine 1",
    image: "assets/bg_remove.png",
    machine_status: "RUNNING",
    datas: {
      good: 50,
      empty: 3,
      defect: 10,
      inspect: 18,
      material: "demo",
      full_cops: 100,
      half_cops: 50,
      quarter_cops: 25,
      doff_number: 201,
    },
  },

  {
    machine_no: 2,
    machine_name: "Machine 2",
    image: "assets/bg_remove.png",
    machine_status: "STOPPED",
    datas: {
      good: 8,
      empty: 0,
      defect: 2,
      inspect: 8,
      material: "demo",
      full_cops: 6,
      half_cops: 2,
      quarter_cops: 1,
      doff_number: 15,
    },
  },

  {
    machine_no: 3,
    machine_name: "Machine 3",
    image: "assets/bg_remove.png",
    machine_status: "RUNNING",
    datas: {
      good: 16,
      empty: 0,
      defect: 1,
      inspect: 15,
      material: "demo",
      full_cops: 14,
      half_cops: 0,
      quarter_cops: 0,
      doff_number: 30,
    },
  },

   {
    machine_no: 4,
    machine_name: "Machine 4",
    image: "assets/bg_remove.png",
    machine_status: "RUNNING",
    datas: {
      good: 18,
      empty: 0,
      defect: 1,
      inspect: 13,
      material: "demo",
      full_cops: 20,
      half_cops: 5,
      quarter_cops: 9,
      doff_number: 52,
    },
  },

   {
    machine_no: 5,
    machine_name: "Machine 5",
    image: "assets/bg_remove.png",
    machine_status: "RUNNING",
    datas: {
      good: 35,
      empty: 100,
      defect: 80,
      inspect: 30,
      material: "demo",
      full_cops: 54,
      half_cops: 0,
      quarter_cops: 0,
      doff_number: 30,
    },
  },

   {
    machine_no: 6,
    machine_name: "Machine 6",
    image: "assets/bg_remove.png",
    machine_status: "STOPPED",
    datas: {
      good: 16,
      empty: 0,
      defect: 1,
      inspect: 15,
      material: "demo",
      full_cops: 14,
      half_cops: 0,
      quarter_cops: 0,
      doff_number: 30,
    },
  },

   {
    machine_no: 7,
    machine_name: "Machine 7",
    image: "assets/bg_remove.png",
    machine_status: "STOPPED",
    datas: {
      good: 16,
      empty: 0,
      defect: 1,
      inspect: 15,
      material: "demo",
      full_cops: 14,
      half_cops: 0,
      quarter_cops: 0,
      doff_number: 30,
    },
  },

   {
    machine_no: 8,
    machine_name: "Machine 8",
    image: "assets/bg_remove.png",
    machine_status: "RUNNING",
    datas: {
      good: 16,
      empty: 0,
      defect: 1,
      inspect: 15,
      material: "demo",
      full_cops: 14,
      half_cops: 0,
      quarter_cops: 0,
      doff_number: 30,
    },
  },
];

export default machineList;